name: Frontend Dev CI/CD - Build and Deploy to Dev Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      # Frontend 리포지토리 체크아웃
      - name: Checkout Frontend repo
        uses: actions/checkout@v4

      # Node.js 환경 설정
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # React에 적합한 버전 (필요 시 조정)

      # 의존성 설치 및 빌드
      - name: Install dependencies
        run: npm ci

      - name: Debug environment variables
        run: |
          echo "REACT_APP_GITHUB_CLIENT_ID: $REACT_APP_GITHUB_CLIENT_ID"
          echo "REACT_APP_REDIRECT_URI: $REACT_APP_REDIRECT_URI"
          echo "REACT_APP_BACKEND_URI: $REACT_APP_BACKEND_URI"
          echo "REACT_APP_BASE_URL: $REACT_APP_BASE_URL"
        env:
          REACT_APP_GITHUB_CLIENT_ID: ${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}
          REACT_APP_REDIRECT_URI: ${{ secrets.REACT_APP_REDIRECT_URI }}
          REACT_APP_BACKEND_URI: ${{ secrets.REACT_APP_BACKEND_URI }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
      
      - name: Build
        run: CI=false npm run build
        env:
          REACT_APP_GITHUB_CLIENT_ID: ${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}
          REACT_APP_REDIRECT_URI: ${{ secrets.REACT_APP_REDIRECT_URI }}
          REACT_APP_BACKEND_URI: ${{ secrets.REACT_APP_BACKEND_URI }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
      
      - name: Check build output
        run: grep -r "REACT_APP_GITHUB_CLIENT_ID" build/ || echo "Not found in build"
      
        # SHA 앞 7자 추출
      - name: Extract short SHA
        id: vars
        run: echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      # Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-app:${{ steps.vars.outputs.sha_short }}

      # Linkey-infra 리포지토리 체크아웃
      - name: Checkout Linkey-infra repo
        uses: actions/checkout@v4
        with:
          repository: Seollal-TF-TEAM/Linkey-infra
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: linkey-infra

      # react/deployment.yaml 업데이트
      - name: Update image tag in deployment
        working-directory: ./linkey-infra
        run: |
          yq eval '.spec.template.spec.containers[0].image = "${{ secrets.DOCKERHUB_USERNAME }}/react-app:${{ steps.vars.outputs.sha_short }}"' -i react/deployment.yaml

      # 변경 사항 커밋 및 푸시
      - name: Commit and push manifest changes
        working-directory: ./linkey-infra
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add react/deployment.yaml
          git commit -m "feat : [Github Actions] Update react-app image tag to ${{ steps.vars.outputs.sha_short }}"
          git push


